### ISSUE TITLE
SBP: Storage usage

### ISSUE THREAD

**Issue by NachoPal** [gamedaoco/gamedao-protocol#53]
The pallets storage schema and usage is not correct. Some tips and guidance:

- You are duplicating values without any need when they should be if possible gathered in a single struct.
  - E.g. `flow.campaings` and `flow.campaignOwner`. The campaign owner is already in the `GamedaoFlowCampaign` struct. In addition, I don’t see the need of adding the campaign `id` in the struct as it is defined as the `StorageMap` key. It seems that you are unnecessarily duplicating data that is already stored in the main struct object in other `StorageMap` with the same key. It applies to all your pallets (control, flow, etc..)
  - Saving big structs instead of creating many new storage keys to save data of the same item. It is in general better to keep a big struct because you reduce the number of read & writes and reduce the size and complexity of the trie.
  - Be also aware that although wrapping related items in a shared structs is an excellent way to reduce the number of storage reads, at some point the size of the object will begin to incur costs that may outweigh the optimisation in storage reads.
  
- As a consequence of the previous issue, there are too many unnecessary storage read/writes, which affects to the extrinsic weight.
  - E.g. https://github.com/gamedaoco/gamedao-protocol/blob/main/control/src/weights.rs#L74-L75
  - It applies to all pallets where data is unnecessary duplicated
    - https://github.com/gamedaoco/gamedao-protocol/blob/main/flow/src/lib.rs#L750-L784
    - https://github.com/gamedaoco/gamedao-protocol/blob/main/signal/src/lib.rs#L826-L850
    - Some of the fields could be also added directly to the main struct Item (`Org`, `Campaign`, etc)

- Consider using `StorageDoubleMap` instead of a simple `StorageMap` + `Vec`. There is not right answer here, it will really depend on each particular case. E.g: `OrgMembers` could be a `StorageDoubleMap` where the secondary key is the member `AccountId`.
  - If the numbers of members can be very large, making use of `Vec` with `contains` and `binary_search` migh be less optimal for read/write than using `contains_key` for the `StorageDoubleMap`.
  - `Vec` might be only make sense if you need to list the vector items in runtime. In that case, `StorageDoubleMap` would mean a lot of DB reads.
  - For the `OrgMembers` example, since there is not a value to save in the double map, it might cause some storage penalty as you'll need to save at least a `bool` value. Maybe in the future your members have more attributes, so it make sense to create a `Member` struct.
  - Create benchmarks to empirically measure what is the optimal design for each case.

- More information about storage best practices: https://docs.substrate.io/main-docs/build/runtime-storage/#best-practices

If the reason of your storage design is to make it easier to retrieve data, there are better alternatives such as:
  - **Building custom RPC calls** to return filtered, gathered or specific info from storage.
  - **Indexing services**: it can collect information listening to the extrinsics & events and build a enriched relational DB with your storage data

**Comment by 2075** [comment]
Thank you for the input, actually this here: `Saving big structs instead of creating many new storage keys to save data of the same item. It is in general better to keep a big struct because you reduce the number of read & writes and reduce the size and complexity of the trie.` is a very good hint, as the over granular use of the storage was supposed to have many lightweight structs to be more efficient on the reading side. If this kind of optimisation is not required, of course storing in a bigger struct is very welcome and makes things much easier.

The StorageDoubleMap discussion we recently had with @vovacha as well, exactly for your `binary_search` example, thanks for the input!

We also run various indexers now which make retrieval of information more efficient, therefore there will be additional optimisations following soon.

Thanks! @NachoPal

**Comment by vovacha** [comment]
> We also run various indexers now which make retrieval of information more efficient, therefore there will be additional optimisations following soon.

We have a bunch of storage items that are not used internally but are only needed for UI. Since the indexer is responsible for data querying, I think we can rely on it and drastically reduce pallet storage until it's not required for internal purposes.  This way, we can keep only the main table (ex., Campaigns, Orgs, Proposals) and query metadata with Graph. Aggregation should also work (total number of campaigns per org, etc.).
**Example.**
The campaign object already has org_id.
And we have another storage with a list of campaigns by its org_id, which is redundant and also increases complexity from O(1) to O(N) due to vector update.

>  have many lightweight structs to be more efficient on the reading side

Not so many examples here. I see only Org and OrgConfig (fee_model, fee, access, member_limit). I'd suggest merging those just for the sake of simplicity until we need any optimizations.
Also, Proposal and Voting are separated into two, but in this case, structs are bigger, and it also helps structure the code.

@2075 WDYT?
