### ISSUE TITLE
SBP: Documentation

### ISSUE THREAD

**Issue by NachoPal** [gamedaoco/gamedao-protocol#58]
Now Polkadot JS app provides links to the extrinsics. Instead of only providing screenshots, you could copy/paste the extrinsics links into the tutorials to make it easier and a better experience for the user.

**Comment by vovacha** [comment]
@5-mark can you handle this?

**Comment by 5-mark** [comment]
Hi @NachoPal,
unfortunately I could not find links to extrinsics. Can you point me to the docs where its written how to link to extrinsics or have a hint?

thanks,
Inan

**Comment by NachoPal** [comment]
It is in the `encoding details` section. It will redirect you to the decoded call. To submit it you just need to click on `Submission` and select the extrinsic Signer.

**Comment by 5-mark** [comment]
@NachoPal when I was adding some extrinsic links to the doc I realized that there are many dynamic values to edit/add anyway.
Eg. the organisationID which comes as a result from creating an organisation or the campaignID to fund into later or also the proposalID. 
Additionally the user following these links would have to always change their accountID/wallet to transact. Therefore we will keep the docu without the extrinsics links.

Meanwhile our frontend made some progress so that a step by step documentation for the web frontend makes more sense. 

Still was a helpful recommendation, thanks.
